image: registry.gitlab.com/tvaughan/gitlab-ci-docker-builder:latest

services:
  - docker:dind

variables:
  GITLAB_USERNAME: gitlab-ci-token

stages:
  - check
  - push

check:
  stage: check
  script:
    - | # TODO: Cannot use GitLab CI variables in `variables:` section.
      export GITLAB_PASSWORD=$CI_BUILD_TOKEN
      make lint
      make test

push:
  stage: push
  script:
    - | # TODO: Cannot use GitLab CI variables in `variables:` section.
      export GITLAB_PASSWORD=$CI_BUILD_TOKEN
      make push
