image: registry.gitlab.com/tvaughan/gitlab-ci-docker-builder:latest

variables:
  GITLAB_USERNAME: gitlab-ci-token
  PODMAN_VM: kibit-runner

cache:
  key: $CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID
  paths:
    - kibit-runner-*.tar

stages:
  - build
  - check
  - push
  - publish

export:
  stage: build
  script:
    - | # TODO: Cannot use GitLab CI variables in `variables:` section.
      export GITLAB_PASSWORD=$CI_BUILD_TOKEN
      make export

lint:
  stage: check
  script:
    - | # TODO: Cannot use GitLab CI variables in `variables:` section.
      export GITLAB_PASSWORD=$CI_BUILD_TOKEN
      make import
      make lint

test:
  stage: check
  script:
    - | # TODO: Cannot use GitLab CI variables in `variables:` section.
      export GITLAB_PASSWORD=$CI_BUILD_TOKEN
      make import
      make test

push:
  stage: push
  script:
    - | # TODO: Cannot use GitLab CI variables in `variables:` section.
      export GITLAB_PASSWORD=$CI_BUILD_TOKEN
      make import
      make push

publish:
  stage: publish
  script:
    - | # TODO: Cannot use GitLab CI variables in `variables:` section.
      export GITLAB_PASSWORD=$CI_BUILD_TOKEN
      make import
      make publish
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/'
