((nil . ((cider-clojure-cli-parameters . "-A:koacha:user -M -m nrepl.cmdline --bind 0.0.0.0 --port 5309 --middleware '%s'")
         (cider-default-cljs-repl . shadow)
         (cider-ns-refresh-after-fn . "devtools.core/run!")
         (cider-ns-refresh-before-fn . "devtools.core/shutdown!")
         (cider-preferred-build-tool . clojure-cli)
         (cider-shadow-cljs-command . "clojure -M:shadow")
         (cider-shadow-default-options . "ui")
         (nrepl-connect-host . "localhost"))))
